#services:
#  postgres:
#    image: postgres:15
#    container_name: nbank-postgres
#    environment:
#      POSTGRES_DB: nbank
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  nbank:
#    image: nobugsme/nbank:with_fraud_check
#    container_name: nbank-app
#    ports:
#      - "4111:4111"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nbank
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      FRAUD_DETECTION_SERVICE_URL: http://host.docker.internal:8080
#    depends_on:
#      postgres:
#        condition: service_healthy
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:4111/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s
#
#volumes:
#  postgres_data:

services:
  backend:
    image: nobugsme/nbank:with_validation_fix
    ports:
      - "4111:4111"
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:latest
    expose:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network
  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: [ "-container-network", "nbank-network" ]
    depends_on:
      - frontend
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      - selenoid
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network