name: Run tests

#trigger
on:
  push:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  run-tests:
    name: Set up services and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository #copy files into ci
        uses: actions/checkout@v4

      - name: Set up Jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '19'

      - name: Cache maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project (no tests)
        run: mvn clean install -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Set up Services
        run: |
            cd infra/docker_compose
            bash restart_docker.sh

      - name: Run all tests
        run: |
          ./mvnw clean test -Papi
        env:
          BASEAPIURL: http://localhost:4111
          BASEUIURL: http://frontend

#          Прогнали тесты → собрали Allure результаты
#
#          Собрали swagger coverage
#
#          Подтянули историю прошлых отчётов
#
#          Собрали новый отчет
#
#          Добавили туда swagger отчёт
#
#          Опубликовали на GitHub Pages

      - name: Run Swagger coverage
        if: always()
        run: .swagger-coverage-commandline/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i target/swagger-coverage-output

      - name: Check API coverage
        if: always()
        run: bash checkCover.sh

      - name: Load test report history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Build Swagger coverage report
        if: always()
        run: sudo cp swagger-coverage-report.html allure-history/${{ github.run_number }}

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Clean up services
        if: always()
        run: cd infra/docker_compose && docker compose down


      - name: Build docker image
        run: |
          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t nbank-tests:$COMMIT_HASH .

      - name: Make push executable
        run: chmod +x ./push-test.sh

      - name: Run docker push script
        run: |
          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          ./push-test.sh "$COMMIT_HASH"
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}