name: Run tests

#trigger
on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Set up services and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository #copy files into ci
        uses: actions/checkout@v4

      - name: Set up Jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '19'

      - name: Cache maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Services
        run: |
            cd infra/docker_compose
            bash restart_docker.sh

      - name: Run all tests
        run: |
          ./mvnw test -Pui
        env:
          BASEAPIURL: http://localhost:4111
          BASEUIURL: http://localhost:3000
          CONFIGURATION_REMOTE: http://localhost:4444/wd/hub
